Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-01, with the labels that each got.

#161 Add recording and alerting rules for TrustyAI
  components/component.go
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  controllers/dscinitialization/monitoring.go
Labels: enhancement, rhods-2.6

#160 update: rebranding for rhoai from rhods
  README.md
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/dashboard/dashboard.go
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/monitoring/alertmanager/alertmanager-configs.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  pkg/deploy/setup.go
Labels: rhods-2.6

#164 fix: couple of changes
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/modelmeshserving/modelmeshserving.go
  controllers/dscinitialization/servicemesh_setup.go
  get_all_manifests.sh
  pkg/deploy/setup.go
  pkg/feature/templates/servicemesh/base/control-plane-disable-networkpolicies.patch.tmpl
  tests/integration/features/servicemesh_feature_test.go
Labels: rhoai-2.6

#173 fix: adding logic to apply trustyai prometheus
  components/trustyai/trustyai.go
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: rhoai-2.6
