Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-09, with the labels that each got.

#342 [backport] fix: dashboard image not get set in downstream due to devFlags conf (#1224)
  components/dashboard/dashboard.go
Labels: approved, lgtm

#344 fix: do not apply resource till applyparams() calls
  components/workbenches/workbenches.go
Labels: approved, lgtm

#349 add permissions to access prometheuses/api
  config/monitoring/prometheus/base/prometheus-rolebinding-viewer.yaml
Labels: approved, lgtm, ok-to-test

#351 prometheus: Update to ClusterRoleBinding
  config/monitoring/prometheus/base/prometheus-rolebinding-viewer.yaml
Labels: approved, lgtm

#343 fix: workbench deployment + change path for its manifests in build
  components/workbenches/workbenches.go
  get_all_manifests.sh
  pkg/cluster/const.go
Labels: approved, lgtm, rhoai-2.14

#322 DSC, DSCI: add validating webhook (#711)
  Makefile
  PROJECT
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/monitoring/networkpolicy/operator/operator.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  main.go
  tests/e2e/creation_test.go
Labels: approved, lgtm, rhoai-2.14

#314 fix: allow admin to login to operator pod from OCM Web Terminal
  config/monitoring/networkpolicy/operator/operator.yaml
Labels: approved, lgtm, rhoai-2.14

#348 RHOAIENG-8512: Implement unit tests for codeflare alerts
  tests/prometheus_unit_tests/codeflare_alerts_unit_tests.yaml
Labels: approved, lgtm, rhoai-2.14, ok-to-test, monitoring

#356 RHOAIENG-12537: Improve Searchability of RHOAI in Operator Catalog
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
Labels: approved, lgtm, rhoai-2.14

#363 [sync] fix: update DSC/DSCI .status.release not depend on other's reconcile
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: approved, lgtm, rhoai-2.14
