Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-04, with the labels that each got.

#236 [sync]: from ODH to RHOAI
  components/dashboard/dashboard.go
  components/kserve/kserve_config_handler.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/utils.go
  pkg/cluster/cluster_config.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/resources.go
  pkg/deploy/deploy.go
  pkg/feature/manifest.go
  pkg/feature/manifest_test.go
  pkg/feature/servicemesh/resources.go
  pkg/metadata/labels/types.go
  pkg/monitoring/monitoring.go
  pkg/plugins/addLabelsplugin.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_cfmap_deletion_test.go
  tests/integration/features/manifests_int_test.go
Labels: rhoai-2.9

#237 Revert "kserve: add grpconly envoy filter (#888)"
  components/kserve/servicemesh_setup.go
  pkg/feature/templates/servicemesh/kserve/grpc-envoyfilter-temp-fix.tmpl
Labels: rhoai-2.9

#234 Altering alert from 0.99950 to 0.98
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: rhoai-2.9

#243 [04/12/24] Sync upstream changes
  components/datasciencepipelines/datasciencepipelines.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
  go.mod
  go.sum
  main.go
  pkg/deploy/deploy.go
Labels: main

#238 update(CSV): annontation for features
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
Labels: main

#247 Revert "Revert "feat(DW): prepare CF,ray,kueue for GA (#929)""
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
Labels: rhoai-2.9

#249 [backport]ray: Cleanup opendatahub Namespace
  pkg/upgrade/upgrade.go
Labels: rhoai-2.8.2

#252 fix: remove duplicated call to the upgrade function in main.go
  main.go
Labels: rhoai-2.9

#253 [backport]: fix: remove duplicated call to the upgrade function in main.go
  main.go
Labels: main
