Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-06, with the labels that each got.

#283 fix: wrong default value for DW components
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#281 fix: missing entry for kueue and kfto in monitoring
  components/component.go
  controllers/dscinitialization/monitoring.go
Labels: approved, lgtm

#284 cherry-pick: ODH PR 989 -- remove cleanup for upgrade from v1 to v2
  main.go
  pkg/upgrade/upgrade.go
Labels: approved, lgtm

#282 feat: re-enable TrustyAI in downstream but set to removed (T.P)
  Makefile
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/component.go
  components/trustyai/trustyai.go
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
Labels: approved, lgtm

#280 test: fix test for rhoai to be used for e2e weekly
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
Labels: approved, lgtm

#286 Revert "feat: re-enable TrustyAI in downstream but set to removed (T.P)"
  Makefile
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/component.go
  components/trustyai/trustyai.go
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
Labels: approved, lgtm

#287 Sync from odh to rhoai 2.11
  .github/PULL_REQUEST_TEMPLATE.md
  Dockerfiles/toolbox.Dockerfile
  Makefile
  OWNERS
  OWNERS_ALIASES
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/tests/scorecard/config.yaml
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/feature_resources.go
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  components/kserve/serverless_setup.go
  components/kserve/servicemesh_setup.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/external/operators.coreos.com_operatorconditions.yaml
  config/scorecard/patches/basic.config.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/feature_resources.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/dscinitialization/suite_test.go
  docs/api-overview.md
  go.mod
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/operator.go
  pkg/cluster/resources.go
  pkg/deploy/deploy.go
  pkg/feature/builder.go
  pkg/feature/conditions.go
  pkg/feature/resources.go
  pkg/feature/servicemesh/conditions.go
  pkg/feature/servicemesh/resources.go
  pkg/plugins/addLabelsplugin.go
  pkg/plugins/namespacePlugin.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/integration/features/manifests_int_test.go
  tests/integration/features/resources_int_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: approved, lgtm, do-not-merge/invalid-owners-file

#290 fix: we should no have this logic in RHOAI
  components/kserve/servicemesh_setup.go
Labels: approved, lgtm

#295 fix: add odh-modle-controller NWP to whitelist (#1087)
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: approved
