Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-02, with the labels that each got.

#184 [cherry-pick]: upstream change for var name
  components/kueue/kueue.go
Labels: rhoai-2.7

#186 [sync]: from main to 2.7 release
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
Labels: rhoai-2.7

#191 sync: from upstream to 2.7
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/suite_test.go
  main.go
  pkg/deploy/deploy.go
  pkg/upgrade/upgrade.go
Labels: rhoai-2.7

#190 [backport]: from 2.6 to 2.7 (#173)
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: rhoai-2.7

#189 [backport] from 2.6 to main (#173)
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: main

#192 Fix Manual Installation of Kserve
  components/kserve/kserve.go
Labels: rhoai-2.7

#196 Remove Trustyai installation in downstream
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/trustyai/trustyai.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
  main.go
  pkg/upgrade/upgrade.go
Labels: rhoai-2.7

#185 Fix(kueue): missing kueue in init-resource section
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/kueue/kueue.go
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
Labels: main

#199 [cherry-pick]: upstream to downstream for webhook
  Makefile
  PROJECT
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/redhat-ods-operator-webhook-service_v1_service.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  main.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
Labels: rhoai-2.8

#201 Rhoai 2.8 sync
  Makefile
  PROJECT
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/redhat-ods-operator-webhook-service_v1_service.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/dashboard/dashboard.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/manifests/kustomization.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  config/samples/dscinitialization_v1_dscinitialization.yaml
  config/samples/featuretracker_v1_features.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  get_all_manifests.sh
  main.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
Labels: rhoai-2.8

#206 cleanup(rhods-monitor-federation2): should not apply again
  config/monitoring/base/rhods-servicemonitor.yaml
Labels: rhoai-2.8
