Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-03, with the labels that each got.

#169 update(CSV): more annotation for features.
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
Labels: rhoai-2.8

#209 Remove references to trustyAI manifests
  components/component.go
  components/trustyai/trustyai.go
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
  main.go
Labels: rhoai-2.8

#202 Sync kserve raw deployments
  OWNERS
  OWNERS_ALIASES
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  docs/Dev-Preview.md
  pkg/deploy/deploy.go
  pkg/feature/feature.go
Labels: rhoai-2.8

#210 [cherrypick]: change for getting odhdashboardconfig with new struct in
  components/dashboard/dashboard.go
Labels: rhoai-2.8

#215 [cherrypick]: add DSPv2 images
  components/datasciencepipelines/datasciencepipelines.go
Labels: rhoai-2.9

#216 Revert "DSC, DSCI: add validating webhook"
  Makefile
  PROJECT
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/redhat-ods-operator-webhook-service_v1_service.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  main.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
Labels: rhoai-2.9

#217 Integrate Authorino for Kserve
  Makefile
  apis/dscinitialization/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/kserve/kserve.go
  components/kserve/servicemesh_setup.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/servicemesh_setup.go
  infrastructure/v1/servicemesh_types.go
  infrastructure/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster_config.go
  pkg/deploy/deploy.go
  pkg/deploy/setup.go
  pkg/feature/builder.go
  pkg/feature/conditions.go
  pkg/feature/feature.go
  pkg/feature/manifest.go
  pkg/feature/serverless/conditions.go
  pkg/feature/serverless/loaders.go
  pkg/feature/serverless/resources.go
  pkg/feature/servicemesh/cleanup.go
  pkg/feature/servicemesh/conditions.go
  pkg/feature/servicemesh/loaders.go
  pkg/feature/servicemesh/resources.go
  pkg/feature/templates/servicemesh/authorino/auth-smm.tmpl
  pkg/feature/templates/servicemesh/authorino/base/operator-cluster-wide-no-tls.tmpl
  pkg/feature/templates/servicemesh/authorino/deployment.injection.patch.tmpl
  pkg/feature/templates/servicemesh/authorino/mesh-authz-ext-provider.patch.tmpl
  pkg/feature/templates/servicemesh/kserve/activator-envoyfilter.tmpl
  pkg/feature/templates/servicemesh/kserve/envoy-oauth-temp-fix.tmpl
  pkg/feature/templates/servicemesh/kserve/kserve-predictor-authorizationpolicy.tmpl
  pkg/feature/templates/servicemesh/kserve/z-migrations/kserve-predictor-authorizationpolicy.patch.tmpl
  pkg/feature/types.go
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_cfmap_deletion_test.go
  tests/integration/features/crd/subscription.crd.yaml
  tests/integration/features/features_int_test.go
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/fixtures/knative_resources.go
  tests/integration/features/fixtures/servicemesh_resources.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: rhoai-2.9

#222 [cherry-pick]: dspv2 update manifests path for new overlay struct (#891)
  components/datasciencepipelines/datasciencepipelines.go
Labels: rhoai-2.9

#219 [cherry-pick]: from incubation to 2.9 for grpc EnvoyFilter
  Dockerfiles/Dockerfile
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/infrastructure/v1/cert_types.go
  apis/infrastructure/v1/doc.go
  apis/infrastructure/v1/serverless_types.go
  apis/infrastructure/v1/servicemesh_types.go
  apis/infrastructure/v1/zz_generated.deepcopy.go
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  components/kserve/servicemesh_setup.go
  pkg/feature/builder.go
  pkg/feature/cert.go
  pkg/feature/handler.go
  pkg/feature/templates/servicemesh/kserve/grpc-envoyfilter-temp-fix.tmpl
  pkg/feature/types.go
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: rhoai-2.9

#224 update(dashboard): do not set owner on CR
  pkg/deploy/deploy.go
  pkg/upgrade/upgrade.go
Labels: rhoai-2.10

#227 [rhoai-2.9] sync from upstream incubation to main for 2.9 release
  Makefile
  README.md
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/infrastructure/v1/groupversion_info.go
  components/README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secretgenerator_controller.go
  crd-ref-docs.config.yaml
  docs/DESIGN.md
  docs/Dev-Preview.md
  docs/api-overview.md
  docs/images/OperatorHub ODH Operator.png
  go.mod
  go.sum
  main.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/cluster_operations_suite_int_test.go
  pkg/cluster/meta.go
  pkg/cluster/resources.go
  pkg/deploy/deploy.go
  pkg/deploy/setup.go
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/manifest.go
  pkg/feature/manifest_test.go
  pkg/feature/raw_resources.go
  pkg/feature/servicemesh/resources.go
  pkg/feature/types.go
  pkg/monitoring/monitoring.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/upgrade/upgrade.go
  tests/integration/features/features_int_test.go
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/templates/fake-kust-dir/kustomization.yaml
  tests/integration/features/templates/fake-kust-dir/resource.yaml
Labels: rhoai-2.9

#226 [rhoai-2.9] Keep Trustyai manifests references
  components/trustyai/trustyai.go
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  main.go
Labels: rhoai-2.9

#221 [cherry-pick]: remove label on operator namespace
  components/workbenches/workbenches.go
  controllers/dscinitialization/utils.go
  pkg/upgrade/upgrade.go
Labels: rhoai-2.9

#225 Keep Trustyai manifests references
  components/trustyai/trustyai.go
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  main.go
Labels: rhoai-2.9
