Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-08, with the labels that each got.

#317 [sync] chore: rename variable/function name
  pkg/deploy/deploy.go
  pkg/plugins/removerplugin.go
  tests/e2e/dsc_creation_test.go
Labels: approved, lgtm, rhoai-2.12

#313 [sync] fix: devFlags for dashboard did not set correct values (#1136)
  components/dashboard/dashboard.go
Labels: approved, lgtm, rhoai-2.12

#321 sync: fix for managed cluster upgrade with DSC already exists (#305)
  pkg/cluster/resources.go
Labels: approved, lgtm

#324 go.mod force version golang.org/x/net v0.23.0, CVE-2023-45288
  go.mod
  go.sum
Labels: approved, lgtm, rhoai-2.8.5

#327 sync: fix for managed cluster upgrade with DSC already exists (#305)
  pkg/cluster/resources.go
Labels: approved, lgtm

#328 fix incorrect label in dashboard SLO probe alerts
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: approved, lgtm, needs-ok-to-test

#334 [sync] open root group to the same permission as owner
  Dockerfiles/Dockerfile
Labels: approved, lgtm, rhoai-2.13

#335 Don't restrict the nbc image update to downstream only (#1170)
  components/workbenches/workbenches.go
Labels: approved, lgtm, rhoai-2.13

#338 [sync]: deps: controller-runtime and code change accordingly (#1189)
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/kserve/kserve_config_handler.go
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/suite_test.go
  controllers/secretgenerator/secretgenerator_controller.go
  go.mod
  go.sum
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/operator.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
Labels: approved, lgtm, rhoai-2.13

#339 [sync] chore: remove dead code (#1203)
  controllers/dscinitialization/dscinitialization_controller.go
Labels: approved, lgtm, rhoai-2.13

#336 [sync] feat: add predicates on deployment (#1172)
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/deploy/deploy.go
Labels: approved, rhoai-2.13

#337 [sync]: "fix: add check for all platform offering on components" + "loggers"
  Makefile
  README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  components/kserve/servicemesh_setup.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/resources.go
  pkg/common/common.go
  pkg/deploy/deploy.go
  pkg/logger/logger.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/resources_int_test.go
Labels: approved, rhoai-2.13
