Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-05, with the labels that each got.

#248 [backport]: 2.9 to main
  pkg/upgrade/upgrade.go
Labels: main

#258 add basic alerting for Kueue
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: main, rhoai-2.9

#263 Added KFTO alerting rule
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: main, rhoai-2.10

#266 Addding kfto component to odh operator (#944)
  README.md
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/component.go
  components/trainingoperator/trainingoperator.go
  components/trainingoperator/zz_generated.deepcopy.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  docs/DESIGN.md
  docs/api-overview.md
  get_all_manifests.sh
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
Labels: main
