Repository red-hat-data-services/rhods-operator, pull requests merged in 2024-10, with the labels that each got.

#367 [sync]fix: add downstream operator namespace into cache for secret (#1267)
  main.go
Labels: approved, lgtm, rhoai-2.14

#368 [sync] feat: add support for upgrade to force disableModelRegistry to false
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, rhoai-2.14

#369 [sync] fix: fixed typo for jackdelahunt owner
  OWNERS_ALIASES
Labels: lgtm, needs-ok-to-test

#372 fix: add missing rbac rule to scrape metrics endpoints protected by rbac, fixes RHOAIENG-13957
  config/monitoring/prometheus/base/prometheus-roles.yaml
Labels: approved, lgtm

#378 [sync]fix: update release version in DSCI and DSC .status for upgrade case
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: main, approved, lgtm, rhoai-2.15

#373 [sync]fix: add release status to upgrade case
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: approved, lgtm, rhoai-2.14

#379 Adding Dockefile for Konflux transition
  Dockerfiles/Dockerfile.konflux
Labels: approved, lgtm

#380 [sync]:feat: Operator disable create usergroup if detect user enable external auth
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/crd/external/config.openshift.io_authentications.yaml
  config/rbac/role.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/suite_test.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
Labels: approved, lgtm, rhoai-2.13.1

#375 update: CSV parts missing in downstream for rhoai 2.15
  Makefile
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
Labels: approved, lgtm, rhoai-2.15

#376 [Sync]: ODH to RHOAI 2.15: validation on namespace
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/infrastructure/v1/servicemesh_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  docs/api-overview.md
Labels: approved, lgtm, rhoai-2.15

#383 [sync]:feat: Operator disable create usergroup if detect user enabl external auth
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/crd/external/config.openshift.io_authentications.yaml
  config/rbac/role.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/suite_test.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
Labels: approved, rhoai-2.15

#433 update: make TrustyAI GA
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  docs/DESIGN.md
  docs/upgrade-testing.md
  get_all_manifests.sh
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
Labels: approved, lgtm

#492 update: remove dsp with v1(tekton)backend related code (#1281)
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/datasciencepipelines/datasciencepipelines.go
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  docs/api-overview.md
Labels: approved

#524 update: release branch to 2.16
  get_all_manifests.sh
Labels: approved, lgtm
